### ISSUE TITLE
Bot Wont Respond

### ISSUE THREAD

**Issue by ClearlyElevated** [Tansc161/Libereus#1] opened 2019-07-11 06:33 UTC
The bot wont respond. I setup everything and started the bot and it says this.
```VancP@DESKTOP-DIMD0M4 MINGW64 ~/Desktop/Libereus
$ py -3 bot.py
Console support non-bmp character. 🎉
Logged in as Libereus v1.0#8241
```

**Comment by Proladon** [comment] 2019-07-11 07:00
Yah, that means successful startup.
the problem was i had commits wrong prefix early today. 
so u can just go to `bot.py` change `line 21`
```python
bot = Bot(command_prefix=commands.when_mentioned_or('[', 'libereus'), pm_help=None, loop=loop)
```
change ' [ ' to ' / ' or what ever u want

**Comment by rixinsc** [comment] 2019-07-11 13:54
The `Logged in as username#0000` line indicates the bot has successfully started.
As Proladon mentioned above, the issue is most likely due to an incorrect prefix used, and it has defaulted in the subsequent commit, either pulling again or changing the code works. :)
For your information, the bot's default prefix is `/` and `libereus`. Directly mentioning it works too.

PS: Just realised that the bot still lacks proper usage documentation LOL, it will be added in the near future.
Be sure to let me know if it works! I'd be happy to help you out if there's any further issue.

**Comment by ClearlyElevated** [comment] 2019-07-11 14:05
Is there a way to set a log channel?

**Comment by rixinsc** [comment] 2019-07-11 14:08
Currently, no. But it will be added in the future release.
Stay tuned!

**Comment by rixinsc** [comment] 2019-07-17 15:40
Closed as no further issue.

**Closed as completed by rixinsc** 2019-07-17 15:40 UTC
